test:
  password_pepper: 5c6198d1c924145529325d62924103e217c4a319c0485a4e219bb1e2c17e1935fe1efb073c8ffb07646295d371e527cc0d79673cd74e1e74347daf5d7dfc1e85
  secret_key_base: 4025b52aaa24e0dc52b161e1180a77ff3021e6a4c5b2475283ad280ad0c58958b63d915516d1fcd3becebee5a8bfd1e6080514c10397e1baee51843ec9300ce7
  oidc_idp_pepper: 54d11ced0702d81356e8913f86d5c059c142d22a2c93b6cda446105580e5ce5f9dfd7c3d2380a5feb96cac7d2013e2b4c7b1edb42df0f22a1158e73bcc6fd02b
  oidc_idp_private_key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDFyYhdyEdLAKGN
    Dk4GxL1QPXVgwZ7aChUx7vhqQ4O9lXejQHWon0YI04kRqLUe67Vy3xSOzlJdbkBY
    BBR6QWgCHN8GR7qc/+t3OB+tQETU/XcipceE7npnSiFKmh+jYfCfjCSk+qkyGyz2
    M7Wpvk61fmax+UQ1DxWRq3uhWiQiUhqzD/usGj9bPj6c5ntrpIjsNd1cjduSDnUJ
    sMI/y9pLOw7yQS0Q5/l7G2bI61sTCB0bojO6JKnSXM8kfE2Uyn5zH7/1hTVR09ee
    /PrVl+bbpnc7rT/BY0/bzka1Z3v+7QkdIWYvm4fg3t0gfLFYEuttI10mWCxWBmJm
    gDkUFjRRAgMBAAECggEBAKhKMWiyp86ui8csm8FwlzB2CrC4LoSRvbUOA3rPVYHz
    cqeKilJeq0WJUAChjvLvViWWoLRd44Ex9TeuyQm5K1lY3X9HewZpTx3SuEk+/RJJ
    VJw7eIeoLqhCUA9dEnx/MjFfGjLyQRKsQtZ96x2yGuCc256lXJ7U5eJbicchnss/
    l7o0t7xXc2sckB1WPnSckOtIICbtWyAQoRiVfltiRRI8B3jb1UC5kDMfvo1Z3A7T
    ARJjOAepwuo4ye5am8t9AALgzp0eSx2ThCSkF2gVrWPWt/GBGP8nNrnJY3fOAjDy
    ClueEMY2lM+ey+cwsxeo5sXfb8jcnZO9viAhg3HsB1ECgYEA65B/oiTWgP5ZHIG9
    oZy8Zbfe1K8siNKp/ggSsiJYBXWjeg4RP8fO3M40YT1B0nKf8piCew/Np9ERfIx1
    74vqj4Ry8pMS5+mjiQ8RC34KyrVhXL6/N5HB8NglC0vGG4ejnGU/t2KE/Ci5NkHp
    XWJXMb3p8tyAbDcaDeINo7P890UCgYEA1vIQYmlSezppx8plQ0sEFGLH6EZWBl9H
    hM4ydnNOzKfcs/HGVi8ftZyxPu94XkqI3NVFeYJuuLd4Uk79tCUa2HOSbh2MHZ3j
    wENkFQEsgJqxjxOPbQXpijy6v+dlDY9T/KJSKo0OyFOv6F8x3grExZzQYMB6Vpkp
    l1Z/1axFw50CgYAByVG+eAsMZWFlnvJCNH8VQmS1NjLfQsG5RHRn12zVdcPsnAiz
    dB90ezfYeO9z2hyuaUusBT2pBSPdzu7iByybNATvJABjs9jipDOb47PPP7riSiwH
    Dtrqqaj2QffZo5ixCe+Gw3+Argphh/RuGd3RacBJcDSlHXHcIxe5YxcLBQKBgQCc
    MSRUzuH/58+MPffdsXpScgGAOPQ0BzKKP+gNiPbe4rAPFoagg/fP2gA2kn9uTU0s
    49FrXaulkLTfYsUbDcd3OGxUliYGM4CXaqEkXkj/Xund5UHY4G33ZO/zmWsmMlu+
    fhmlEAGI8r8l5V7wUfTxAGWvmM6NdRjy/wk/tMKxRQKBgQC5+vFCFQGXRG7L/ZFm
    +5zJbVde6FZ25TlHFyQCYtFkdK7/xstXzLYU95fJzA/wBPdfkdvMP1Xv4NCmnNES
    pG3pmuZoDHAkUKrpab23bVx6ga75G+LBLr8m9shFFJm+I7wYyTUzqnh2m6iC7xW3
    ccMzoDPG9YOgQ8j/0/clZTEiJA==
    -----END PRIVATE KEY-----

development:
  notify_api_key: <%= ENV['NOTIFY_API_KEY'] %>
  password_pepper: 18dbba12fe3f599ce7cec24fd7b7bddb4d0fd1c5d14723f40ee9d2a2110b42c566574b8d900c806e6a23bf7105df80f480ad1261ba3ba2d745be8e7b89971b58
  secret_key_base: 6b2ce73ed560001c389eee4a3193abc41405cd405f663137b769fe98c0f9e689e9bbb82530b8de03b06f2ed85ced17b60b6dfac77c6c997e18bf7776de526c4c
  oidc_idp_pepper: b7472a2e32355909d86da714456da2bd5f9a0795ba3737a80034355f92b47e22ca465adad9a8dbe532ae44de035989a5a2ce652c3cc6117e0e9bc3a8cb755363
  oidc_idp_private_key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDFyYhdyEdLAKGN
    Dk4GxL1QPXVgwZ7aChUx7vhqQ4O9lXejQHWon0YI04kRqLUe67Vy3xSOzlJdbkBY
    BBR6QWgCHN8GR7qc/+t3OB+tQETU/XcipceE7npnSiFKmh+jYfCfjCSk+qkyGyz2
    M7Wpvk61fmax+UQ1DxWRq3uhWiQiUhqzD/usGj9bPj6c5ntrpIjsNd1cjduSDnUJ
    sMI/y9pLOw7yQS0Q5/l7G2bI61sTCB0bojO6JKnSXM8kfE2Uyn5zH7/1hTVR09ee
    /PrVl+bbpnc7rT/BY0/bzka1Z3v+7QkdIWYvm4fg3t0gfLFYEuttI10mWCxWBmJm
    gDkUFjRRAgMBAAECggEBAKhKMWiyp86ui8csm8FwlzB2CrC4LoSRvbUOA3rPVYHz
    cqeKilJeq0WJUAChjvLvViWWoLRd44Ex9TeuyQm5K1lY3X9HewZpTx3SuEk+/RJJ
    VJw7eIeoLqhCUA9dEnx/MjFfGjLyQRKsQtZ96x2yGuCc256lXJ7U5eJbicchnss/
    l7o0t7xXc2sckB1WPnSckOtIICbtWyAQoRiVfltiRRI8B3jb1UC5kDMfvo1Z3A7T
    ARJjOAepwuo4ye5am8t9AALgzp0eSx2ThCSkF2gVrWPWt/GBGP8nNrnJY3fOAjDy
    ClueEMY2lM+ey+cwsxeo5sXfb8jcnZO9viAhg3HsB1ECgYEA65B/oiTWgP5ZHIG9
    oZy8Zbfe1K8siNKp/ggSsiJYBXWjeg4RP8fO3M40YT1B0nKf8piCew/Np9ERfIx1
    74vqj4Ry8pMS5+mjiQ8RC34KyrVhXL6/N5HB8NglC0vGG4ejnGU/t2KE/Ci5NkHp
    XWJXMb3p8tyAbDcaDeINo7P890UCgYEA1vIQYmlSezppx8plQ0sEFGLH6EZWBl9H
    hM4ydnNOzKfcs/HGVi8ftZyxPu94XkqI3NVFeYJuuLd4Uk79tCUa2HOSbh2MHZ3j
    wENkFQEsgJqxjxOPbQXpijy6v+dlDY9T/KJSKo0OyFOv6F8x3grExZzQYMB6Vpkp
    l1Z/1axFw50CgYAByVG+eAsMZWFlnvJCNH8VQmS1NjLfQsG5RHRn12zVdcPsnAiz
    dB90ezfYeO9z2hyuaUusBT2pBSPdzu7iByybNATvJABjs9jipDOb47PPP7riSiwH
    Dtrqqaj2QffZo5ixCe+Gw3+Argphh/RuGd3RacBJcDSlHXHcIxe5YxcLBQKBgQCc
    MSRUzuH/58+MPffdsXpScgGAOPQ0BzKKP+gNiPbe4rAPFoagg/fP2gA2kn9uTU0s
    49FrXaulkLTfYsUbDcd3OGxUliYGM4CXaqEkXkj/Xund5UHY4G33ZO/zmWsmMlu+
    fhmlEAGI8r8l5V7wUfTxAGWvmM6NdRjy/wk/tMKxRQKBgQC5+vFCFQGXRG7L/ZFm
    +5zJbVde6FZ25TlHFyQCYtFkdK7/xstXzLYU95fJzA/wBPdfkdvMP1Xv4NCmnNES
    pG3pmuZoDHAkUKrpab23bVx6ga75G+LBLr8m9shFFJm+I7wYyTUzqnh2m6iC7xW3
    ccMzoDPG9YOgQ8j/0/clZTEiJA==
    -----END PRIVATE KEY-----

production:
  notify_api_key: <%= ENV['NOTIFY_API_KEY'] %>
  password_pepper: <%= ENV['PASSWORD_PEPPER'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  oidc_idp_pepper: <%= ENV['OIDC_IDP_PEPPER'] %>
  oidc_idp_private_key: |
<%= ENV['OIDC_IDP_PRIVATE_KEY']&.gsub(/^/, '    \1') %>
