:queues:
  - mailers
  - default
  - user_password_check

:schedule:
  expire_registration_state:
    cron: "0 */15 * * * *"
    class: ExpireRegistrationStateJob
  expire_login_state:
    cron: "0 */15 * * * *"
    class: ExpireLoginStateJob
  expire_ephemeral_state:
    cron: "0 */15 * * * *"
    class: ExpireEphemeralStateJob
  expire_jwt:
    cron: "0 */15 * * * *"
    class: ExpireJwtJob
